-- Placeholder for '20250901212838_add_property_documents'
-- This file exists so Prisma sees the same migration lineage as the database.
-- The database already reflects the current schema (enforced via db push).
